### ISSUE TITLE
Prepare usability testing of app on tab

### ISSUE THREAD

**Issue by pgdr** [Statoil/BetterTogether#38]
On Friday at 12:00!! (In office landscape or in digilab)

**Comment by pgdr** [comment]
Kristian brings a Chromecast

**Comment by ohald** [comment]
Usability testing:
- Make yourself a new user.
- Change your profile picture.
- You have pair programmed with Magnus Leikvoll. Register a pair programming event.
- You have had a cake event. Tell the app you have used a cake reward.
-  Find out the total number of pair programming events.
- You selected the wrong person before submitting a pair programming event. Undo the selection.
- See if you can find a visualization of the pair programming events.
